# Generated by Django 2.2.28 on 2022-10-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20221018_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicservice',
            name='desc',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mechanicservice',
            name='guest',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
