# Generated by Django 4.1.1 on 2022-10-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mechanicservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicservice',
            name='date',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
