# Generated by Django 4.1.1 on 2022-10-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_mechanicservice_am_mechanicservice_min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanicservice',
            old_name='am',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='mechanicservice',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='mechanicservice',
            name='min',
        ),
    ]
