# Generated by Django 4.1.1 on 2022-10-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_carservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarService',
            new_name='CarServices',
        ),
    ]
