# Generated by Django 4.1.1 on 2022-10-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_carservice_carservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverBookingCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('pickup', models.CharField(max_length=122)),
                ('destination', models.CharField(max_length=122)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
    ]
