# Generated by Django 2.2.28 on 2022-10-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20221020_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('destination', models.CharField(max_length=122)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('desc', models.TextField(max_length=500, null=True)),
                ('guest', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartiesEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('destination', models.CharField(max_length=122)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('desc', models.TextField(max_length=500, null=True)),
                ('guest', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('destination', models.CharField(max_length=122)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('desc', models.TextField(max_length=500, null=True)),
                ('guest', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeddingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('destination', models.CharField(max_length=122)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('desc', models.TextField(max_length=500, null=True)),
                ('guest', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='MechanicService',
            new_name='CollegeEvent',
        ),
        migrations.DeleteModel(
            name='CarBooking',
        ),
        migrations.DeleteModel(
            name='CarServices',
        ),
        migrations.DeleteModel(
            name='DriverBookingCar',
        ),
        migrations.DeleteModel(
            name='RentCar',
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
